### ISSUE TITLE
Installer Version 2

### ISSUE THREAD

**Issue by MikaylaFischler** [MikaylaFischler/cc-mek-scada#194]
- [ ] Show a percentage of progress
- [x] Wait on key press before continuing instead of using `os.sleep`
- [x] #313 Ability to download new installer
- [x] #274 Deleting unused/removed/moved files
- [x] #258 Versioned graphics component
- [x] #282 Versioned common code
- [x] ~~Announcements functionality~~
- [x] ~~Detect in installer if local is actually newer than remote version?~~ just say 'different' rather than 'newer'
- [x] #336 Remove `remove`
- [x] #382 Don't delete mounts (`isDriveRoot()`)
- [x] Prompt to delete unknown root folders
- [x] Properly handle non-standard `log.txt` files
- [x] Remove usage of `config.lua`
- [ ] Remove delete protection of `config.lua` (this won't save that many bytes, probably not recommended)
- [x] Skip extra prompts/dialogs if the update has nothing to actually update
- [x] #568 Remove warning about alternate install method
- [x] #568 Handle insufficient space more gracefully
- [x] #569 Windows case insensitivity mitigation
- [x] #411 ~~Reduce download size/space utilization by not including unused files~~
- [ ] #708 Install minified files
