### ISSUE TITLE
Poly1305 Message Authentication

### ISSUE THREAD

**Issue by MikaylaFischler** [MikaylaFischler/cc-mek-scada#261]
Try an implementation of [Poly1305](https://en.wikipedia.org/wiki/Poly1305) MAC to see if it will be faster than HMAC-MD5 #51.

## Tasks

- [ ] Lockbox implementation of Poly1305
- [ ] Test timings
- [ ] Integrate if faster
- [ ] Unique sequence numbers (must never repeat message contents)

## Notes
https://crypto.stackexchange.com/questions/52009/fastest-algorithm-for-message-authentication
https://crypto.stackexchange.com/questions/64839/gmac-vs-hmac-in-message-forgery-and-bandwidth
https://datatracker.ietf.org/doc/html/rfc8439#section-2.5
https://gist.github.com/josiahcarlson/792634/d1326582d32dda17bf2f339f6db242082ccd2bed
https://crypto.stackexchange.com/questions/56429/which-algorithm-has-better-performance-hmac-umac-and-poly1305

**Comment by MikaylaFischler** [comment]
Pure Lua SHA repo has better performance, this shouldn't be necessary.
