### ISSUE TITLE
Closed Loop Controller Enhancements

### ISSUE THREAD

**Issue by MikaylaFischler** [MikaylaFischler/cc-mek-scada#467]
~~Multi-input single-output PID control of reactors~~
- https://www.osti.gov/biblio/1510860
- https://www.sciencedirect.com/science/article/pii/S0959152420302080

~~Considering adding temperature change as an input and/or coolant level. Possibly implement something like this PLC-side to do ramping in a smarter way.~~

~~Possibly change to pre-compute a ramp rate based on cooling configuration and send that to the PLC.~~

## Tasks

- [x] Rework charge conversion factor calculation to be configuration-aware
- [x] Change moving average filters to EMA filters
- [x] Generation rate rework to adjust feed-forward if needed, dynamically
- [ ] Charge level rework to have two stages of operation and use a feed forward when running closed loop

## 2026/05/28

Focus on enhancement of charge level and generation rate control enhancements. Ramping improvements and fuel awareness are now handled PLC-side. Changing the system to dynamically respond to coolant/temperature statistics will introduce too many moving parts and potentially cause the system to oscillate excessively or otherwise not achieve stability.

### Generation Rate

#725 will change this to use turbine generation rates rather than induction matrix input rate. When using the latter still, this should dynamically re-compute the feed-forward value rather than purely depend on the integrator for corrections, which should improve performance when external power inputs turn on or off.

### Charge Level

Use build properties and burn rate limits to determine a window around the target where ramping and running all assigned units at full burn will not result in overshoot. Once within the window, switch to the PID controller, rather than running it all the time. If we exit the window for too long or by too much, switch back to max burn and reset the PID controller's accumulator.

Calculate (and re-calculate, as needed) a feed-forward component based on the filtered energy outflow from the induction matrix, and use this in the closed loop controller phase to reduce dependence on the integrator and PID control in general.

### Both Modes

Change the filtering to use exponential moving average filters to improve responsiveness and filtering performance.
